### ISSUE TITLE
Decide on the server setup

### ISSUE THREAD

**Issue by amalija-ramljak** [InCogNiTo124/personal-blog#4]
Research the best option for the server - nginx proxy, something with an existing adapter, etc.

Starting point https://kit.svelte.dev/docs#adapters

**Comment by amalija-ramljak** [comment]
Additional resources

https://myrmod.de/posts/how-to-host-a-sveltekit-project-with-docker-https

https://www.reddit.com/r/sveltejs/comments/ookqde/how_do_i_deploy_my_sveltekit_app/

**Comment by InCogNiTo124** [comment]
It seems that serving through node.js seems the easiest

**Comment by amalija-ramljak** [comment]
TODO: test deployment of project skeleton with Node
